//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destination_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order_details
    {
        public int orderId { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Not Null")]
        public int userId { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Not Null")]
        public string orderInfo { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Not Null")]
        public string fromCity { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Not Null")]
        public string toCity { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Not Null")]
        public System.DateTime departureDate { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Not Null")]
        public System.DateTime returnDate { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Not Null")]
        public int peopleNumber { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Not Null")]
        public decimal payment { get; set; }
        public virtual User_details User_details { get; set; }
    }
}
