//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destination_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User_details
    {
        public User_details()
        {
            this.Order_details = new HashSet<Order_details>();
        }
    
        public int userId { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Not Null")]
        public string username { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Not Null")]
        public string password { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Not Null")]
        public string gender { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Not Null")]
        public System.DateTime birthday { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Not Null")]
        public string phone { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Not Null")]
        public string email { get; set; }

        public virtual ICollection<Order_details> Order_details { get; set; }
    }
}
